name: "Cachet"
description: "[DEPRECATED / MIGRATED TO RANCHER2] Cachet - The Open Source Status Page System"
version: "1.7-1"
category: "Monitoring"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
