name: "Volto - Bise"
description: "Volto - Bise: React-based frontend"
version: "3.11.0"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
