name: "CDR Test"
description: "CDR Test Eionet"
version: "6.7.3-212"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.rancher.catalog/blob/master/templates/cdrtest/README.md
labels:
  io.rancher.certified: EEA
