name: "Copernicus Insitu backend - Plone 6"
description: "Copernicus In-situ Plone 6 backend"
version: "6.0.15-11"
category: "Applications"
maintainer: "EEA: IDM2 N-Team"
license: "GPLv3"
projectURL: http://eea.github.io
labels:
  io.rancher.certified: EEA
