name: "Countries and Regions elasticsearch app"
description: "Elasticsearch app for Countries and Regions."
version: "2.0.0"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
