version: "2"
services:
  apache:
    image: eeacms/apache:2.4-3.1
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- if eq .Values.TRAEFIC_ENABLE "true"}}
      traefik.enable: 'true'
      traefik.http.routers.{{ .Values.VOLUME_PREFIX }}land.rule: Host({{ .Values.TRAEFIC_URLS }})
      traefik.http.services.{{ .Values.VOLUME_PREFIX }}land.loadbalancer.server.port: '80'
      {{- if (.Values.TRAEFIC_GEOBLOCK)}}
      traefik.http.middlewares.{{ .Values.VOLUME_PREFIX }}landgeoblock.plugin.geoblock.disallowedCountries: {{ .Values.TRAEFIC_GEOBLOCK }}
      traefik.http.middlewares.{{ .Values.VOLUME_PREFIX }}landgeoblock.plugin.geoblock.disallowedStatusCode: '204'
      traefik.http.middlewares.{{ .Values.VOLUME_PREFIX }}landgeoblock.plugin.geoblock.enabled: 'true'
      traefik.http.routers.{{ .Values.VOLUME_PREFIX }}land.middlewares: {{ .Values.VOLUME_PREFIX }}landgeoblock@rancher
      traefik.http.middlewares.{{ .Values.VOLUME_PREFIX }}landgeoblock.plugin.geoblock.databaseFilePath: /plugins-local/src/github.com/kucjac/traefik-plugin-geoblock/IP2LOCATION-LITE-DB1.IPV6.BIN
      traefik.http.middlewares.{{ .Values.VOLUME_PREFIX }}landgeoblock.plugin.geoblock.allowPrivate: 'true'
      {{- end}}
      {{- end}}
    links:
    - varnish
    mem_reservation: ${APACHE_MEMORY_RESERVATION}
    mem_limit: ${APACHE_MEMORY_LIMIT}
    environment:
      APACHE_MODULES: "${APACHE_MODULES}"
      APACHE_CONFIG: "${APACHE_CONFIG}"
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads
    {{- end}}

  varnish:
    image: eeacms/varnish-copernicus-land:21.7.27
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      VARNISH_BACKEND_HOST: haproxy
      VARNISH_BACKEND_PORT: '5000'
      VARNISH_MEMORY: 2G
      LOGSPOUT: "ignore"
    links:
    - haproxy
    mem_reservation: ${VARNISH_MEMORY_RESERVATION}
    mem_limit: ${VARNISH_MEMORY_LIMIT}

  haproxy:
    image: eeacms/haproxy:1.8-1.7
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    ports:
    - "1936:1936"
    links:
    - plone
    mem_reservation: ${HAPROXY_MEMORY_RESERVATION}
    mem_limit: ${HAPROXY_MEMORY_LIMIT}
    environment:
      TZ: "${TZ}"
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      TIMEOUT_SERVER: "180000"
      TIMEOUT_CLIENT: "180000"
      STATS_AUTH: "${HAPROXY_STATS_AUTH}"

  memcached:
    image: memcached:1.6.20-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - "256"
    - -I
    - "64m"
    mem_reservation: ${MEMCACHED_MEMORY_RESERVATION}
    mem_limit: ${MEMCACHED_MEMORY_LIMIT}

  postfix:
    {{- if eq .Values.VOLUME_PREFIX "demo"}}
    image: eaudeweb/mailtrap:2.3
    mem_reservation: 128m
    mem_limit: 128m
    ports:
    - "80"
   {{- else}}
    image: eeacms/postfix:3.5-1.0
    mem_reservation: ${POSTFIX_MEMORY_RESERVATION}
    mem_limit: ${POSTFIX_MEMORY_LIMIT}
    environment:
      TZ: "${TZ}"
      MTP_HOST: "eea.europa.eu"
      MTP_RELAY: ${POSTFIX_MTP_RELAY}
      MTP_PORT: ${POSTFIX_MTP_PORT}
   {{- end}}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  plone:
    image: eeacms/plone-copernicus-land:23.6.14-2.161
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    mem_reservation: ${PLONE_MEMORY_RESERVATION}
    mem_limit: ${PLONE_MEMORY_LIMIT}
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_client"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/data/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads
    {{- end}}

  async:
    image: eeacms/plone-copernicus-land:23.6.14-2.161
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    mem_reservation: ${ASYNC_MEMORY_RESERVATION}
    mem_limit: ${ASYNC_MEMORY_LIMIT}
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_async"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/data/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads
    {{- end}}

  cron-subscrib-reset:
    image: eeacms/plone-copernicus-land:23.6.14-2.161
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      cron.schedule: 0 0 * * *
    links:
    - zeoserver
    - memcached
    - postfix
    mem_reservation: ${CRONSUBSRESET_MEMORY_RESERVATION}
    mem_limit: ${CRONSUBSRESET_MEMORY_LIMIT}
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_client"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
      SERVER_NAME: "${SERVER_NAME}"
    entrypoint:
    - bin/zeo_client
    - run
    - bin/subscrib_reset
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/data/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads
    {{- end}}

  zeoserver:
    image: plone/zeoserver:2.13.23-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    mem_reservation: ${ZEOSERVER_MEMORY_RESERVATION}
    mem_limit: ${ZEOSERVER_MEMORY_LIMIT}
    volumes:
    {{- if (.Values.DATA_VOLUME_NAME)}}
      - {{ .Values.DATA_VOLUME_NAME }}:/data
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_data:/data
    {{- end}}
    environment:
      TZ: "${TZ}"

  sync-proxy:
    image: nginx:1.21-alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    mem_reservation: ${SYNCPROXY_MEMORY_RESERVATION}
    mem_limit: ${SYNCPROXY_MEMORY_LIMIT}
    environment:
      TZ: "Europe/Copenhagen"
      NGINX_CONF: "${SYNC_PROXY_CONFIG}"
    command:
      - /bin/sh
      - -c
      - 'echo $$NGINX_CONF > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    restart: "always"


  landfiles-sync:
    image: eeacms/copernicus-land-scripts:sync-1.3
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      SOURCE_DIRECTORY: "${SYNC_REMOTE_PATH}"
      TARGET_DIRECTORY: "${SYNC_TARGET_PATH}"
      RCLONE_CONFIG_REMOTE_URL: "${SYNC_REMOTE_URL}"
      TO_ADDRESS: "${TO_ADDRESS}"
      DELETE_OLDER_LOGS: 90
      POSTFIX_SERVER: postfix
      ALWAYS_SEND_EMAIL: "${ALWAYS_SEND_EMAIL}"
      HOURS_MAX_DURATION: "${HOURS_MAX_DURATION}"
      HOURS_WITHOUT_RUN: "${HOURS_WITHOUT_RUN}"
      DEBUG: "${DEBUG}"
    mem_reservation: ${LANDFILESSYNC_MEMORY_RESERVATION}
    mem_limit: ${LANDFILESSYNC_MEMORY_LIMIT}
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads
    {{- end}}
    {{- if (.Values.SYNCLOGS_VOLUME_NAME)}}
      - {{ .Values.SYNCLOGS_VOLUME_NAME }}:/logs
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_logs:/logs
    {{- end}}


  landfiles-cleanup:
    image: eeacms/copernicus-land-scripts:cleanup-1.0
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      TARGET_DIRECTORY: /downloads/landfiles/dst/
    volumes:
    {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
      - {{ .Values.DOWNLOADS_VOLUME_NAME }}:/downloads
    {{- else}}
      - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads
    {{- end}}


volumes:
  {{- if (.Values.DATA_VOLUME_NAME)}}
  {{ .Values.DATA_VOLUME_NAME}}:
  {{- else}}
  {{ .Values.VOLUME_PREFIX }}land_data:
  {{- end}}
    driver: ${DATA_VOLUME_DRIVER}
    external: true

  {{- if (.Values.DOWNLOADS_VOLUME_NAME)}}
  {{ .Values.DOWNLOADS_VOLUME_NAME }}:
  {{- else}}
  {{ .Values.VOLUME_PREFIX }}land_downloads:
  {{- end}}
    driver: ${DOWNLOADS_VOLUME_DRIVER}
    external: true
