name: "EEA - WWW (Plone)"
description: "EEA Plone website"
version: "19.10.23"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.www/
labels:
  io.rancher.certified: EEA
