name: "EEA Website Backend - Plone 6"
description: "EEA Main Website Plone 6 Backend"
version: "6.0.13-24"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io
labels:
  io.rancher.certified: EEA
