version: '2'
services:
  memcached:
    image: memcached:1.5.16
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - '128'
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.hostname_override: container_name
    mem_limit: 256m
    mem_reservation: 256m
  async:
    image: eeacms/plone-copernicus-insitu:20.7.15-4.1
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: zeo_async
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
    stdin_open: true
    tty: true
    links:
    - memcached:memcached
    - zeoserver:zeoserver
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.hostname_override: container_name
    mem_limit: 1g
    mem_reservation: 1g
  plone:
    image: eeacms/plone-copernicus-insitu:20.7.15-4.1
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: zeo_client
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "{{.Environment.Name}} - {{.Stack.Name}}"
    stdin_open: true
    tty: true
    links:
    - memcached:memcached
    - zeoserver:zeoserver
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.hostname_override: container_name
    mem_limit: 1g
    mem_reservation: 1g

  postfix:
    {{- if eq .Values.VOLUME_PREFIX "demo-"}}
    image: eaudeweb/mailtrap:2.3
    ports:
    - "80"
    {{- else}}
    image: eeacms/postfix:eionet
    environment:
      MTP_HOST: eea.europa.eu
      TZ: "${TZ}"
    {{- end}}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.hostname_override: container_name
    mem_limit: 64m
    mem_reservation: 64m

  zeoserver:
    image: plone/zeoserver:2.13.23
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - {{ .Values.VOLUME_PREFIX }}insitu-website-data:/data
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.hostname_override: container_name
    mem_limit: {{ .Values.ZEO_MEM_LIMIT }}
    mem_reservation: {{ .Values.ZEO_MEM_RES }}
volumes:
  {{ .Values.VOLUME_PREFIX }}insitu-website-data:
    external: true
    driver: rancher-ebs

