name: "Bise Backend - Plone"
description: "Bise backend plone site"
version: "10.0.31"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/eea.docker.plone.bise/tree/volto-plone5/backend
labels:
  io.rancher.certified: Eionet
