name: "Bise Backend - Plone"
description: "Bise backend plone site"
version: "11.0.1-1"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/bise-backend/tree/master
labels:
  io.rancher.certified: Eionet
