name: "Volto - Freshwater"
description: "Volto - Freshwater: React-based frontend"
version: "1.13.0.develop.03"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
