name: "EEA - Jenkins (Worker)"
description: "Jenkins Worker"
version: "3.49"
category: "Continuous Integration"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.jenkins/
labels:
  io.rancher.certified: EEA
