name: "Volto - IMS"
description: "Volto - IMS: React-based frontend"
version: "0.6.4"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
