name: "Wise - Plone"
description: "Plone 5 Wise Website"
version: "5.2-1"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/eea.docker.plone.fise
labels:
  io.rancher.certified: EEA
