name: "EEA WWW - Volumes"
description: "Prepare Docker volumes needed by EEA WWW Stack"
version: "1.1-rancher1"
category: "Storage"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
