name: "Marine Backend - Plone 5"
description: "Marine backend for the Plone site"
version: "6.0.15-20"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/marine-backend
labels:
  io.rancher.certified: EEA
