version: '2'
services:
  frontend:
    image: eeacms/ims-frontend:0.9.4
    ports:
    - "3000"
    mem_limit: 4g
    mem_reservation: 1g
    depends_on:
    - backend
    links:
    - backend
    environment:
      SENTRY_URL: ${SENTRY_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SENTRY_ORG: ${SENTRY_ORG}
      SENTRY_PROJECT: ${SENTRY_PROJECT}
      RAZZLE_SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_RELEASE: '0.9.4'
      RAZZLE_SENTRY_RELEASE: '0.9.4'
      RAZZLE_ALLOWED_CORS_DESTINATIONS: ${ALLOWED_CORS_DESTINATIONS}
      API_PATH: ${API_PATH}
      INTERNAL_API_PATH: ${INTERNAL_API_PATH}
      PORT: '3000'
      TZ: "${TZ}"
    labels:
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  {{- if eq .Values.DEBUG "Yes" }}
  debug:
    image: eeacms/ims-frontend:develop  #gitflow-disable - Keep this comment to disable automatic upgrades by gitflow
    ports:
    - "3000"
    mem_limit: 4g
    mem_reservation: 1g
    depends_on:
    - backend
    links:
    - backend
    environment:
      SENTRY_URL: ${SENTRY_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SENTRY_ORG: ${SENTRY_ORG}
      SENTRY_PROJECT: ${SENTRY_PROJECT}
      RAZZLE_SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_RELEASE: '0.9.4'
      RAZZLE_SENTRY_RELEASE: '0.9.4'
      RAZZLE_ALLOWED_CORS_DESTINATIONS: ${ALLOWED_CORS_DESTINATIONS}
      API_PATH: ${API_PATH}
      INTERNAL_API_PATH: ${INTERNAL_API_PATH}
      RAZZLE_API_PATH: ${API_PATH}
      RAZZLE_INTERNAL_API_PATH: ${INTERNAL_API_PATH}
      REBUILD: "True"
      PORT: '3000'
      TZ: "${TZ}"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
    stdin_open: true
    tty: true
    volumes:
    - develop:/opt/frontend/src/addons
    command:
    - cat
  rsync:
    image: eeacms/rsync
    ports:
    - "2222:22"
    environment:
      SSH_AUTH_KEY: "${SSH_AUTH_KEY}"
    stdin_open: true
    tty: true
    volumes:
    - develop:/opt/frontend/src/addons
    command:
    - server
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
  {{- end}}

  backend:
    image: rancher/dns-service
    external_links:
    - ${BACKEND}:backend

{{- if eq .Values.DEBUG "Yes" }}
volumes:
  develop:
    driver: rancher-ebs
    driver_opts:
      size: '1'
{{- end}}
