name: "Volto - Forests"
description: "Volto - Forests: React-based frontend"
version: "2.0-beta.36"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
