name: "Volto - Forests"
description: "Volto - Forests: React-based frontend"
version: "3.1.0"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
