name: "Freshwater Backend - Plone 5"
description: "Freshwater backend for the Plone site"
version: "6.0.15-4"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/freshwater-backend
labels:
  io.rancher.certified: EEA
