name: "EMEP/EEA air pollutant emission inventory â€” Elastic app"
description: "Elasticsearch app for EMEP/EEA air pollutant emission inventory."
version: "1.0.1"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
