name: "EEA Janitor"
description: "Automatic cleanup of unused images on hosts, in order to save disk space"
version: "2.2.2"
category: "Maintenance"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/docker-cleanup
labels:
  io.rancher.certified: EEA
