name: "Danswer AI"
description: "The Open Source, AI-powered search engine across your company's docs, apps, and people"
version: "v2.3.0-eea.0.0.83-dev"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
