name: "Volto - CCA"
description: "Volto - CCA: React-based frontend"
version: "3.28.1-alpha.3"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/cca-frontend
labels:
  io.rancher.certified: EEA
