version: "2"
services:
  esapp:
    image: eeacms/esbootstrap:v3.1.5
    environment:
      VERSION_INFO: eeacms/esbootstrap:v3.1.5
      elastic_host: elastic
      AUTO_INDEXING: 'false'
      elastic_index: co2_cars
      APP_CONFIG_DIRNAME: CO2_passenger_cars
      TZ: ${TZ}
      elastic_rwuser: ${RW_USER}
      elastic_rwpass: ${RW_PASSWORD}
      elastic_rouser: ${RO_USER}
      elastic_ropass: ${RO_PASSWORD}
      elastic_appalias: 'prod'
      API_token: ${API_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
      DASHBOARD_SRC: ${DASHBOARD_SRC}
    ports:
      - '3000'
    labels:
      {{- if .Values.host_labels}}
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
      - esbootstrapdataconfig:/code/config
    links:
      - 'elastic:'
    mem_limit: ${app_mem_limit}
    mem_reservation: ${app_mem_reservation}

  most-recent-sync:
    image: eeacms/esbootstrap:v3.1.5
    environment:
      VERSION_INFO: eeacms/esbootstrap:v3.1.5
      elastic_host: elastic
      AUTO_INDEXING: 'false'
      elastic_index: co2_cars_dashboard
      APP_CONFIG_DIRNAME: CO2_passenger_cars_dashboard
      TZ: ${TZ}
      elastic_rwuser: ${RW_USER}
      elastic_rwpass: ${RW_PASSWORD}
      elastic_rouser: ${RO_USER}
      elastic_ropass: ${RO_PASSWORD}
      elastic_appalias: 'prod'
      API_token: ${API_TOKEN}
      SENTRY_DSN: ${SENTRY_DSN}
      DASHBOARD_SRC: ${DASHBOARD_SRC}
    ports:
      - '3000'
    labels:
      {{- if .Values.host_labels}}
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
      - esbootstrapdataconfig:/code/config
    links:
      - 'elastic:'
    mem_limit: ${app_mem_limit}
    mem_reservation: ${app_mem_reservation}


  esbootstrap-data-config:
    image: eeacms/esbootstrap-configs:v3.0.103
    environment:
      - github_repo=https://github.com/eea/eea.esbootstrap.configs
      - DEV_ENV=false
      - TZ=${TZ}
    volumes:
      - esbootstrapdataconfig:/code/config
    labels:
      io.rancher.container.start_once: 'true'
      {{- if .Values.host_labels}}
      io.rancher.scheduler.affinity:host_label: ${host_labels}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.container.hostname_override: container_name
    mem_limit: 32m
    mem_reservation: 32m
  
  elastic:
    external_links:
      - ${es_endpoint}
    image: rancher/dns-service

volumes:
  esbootstrapdataconfig:
    driver: ${VOLUME_DRIVER}
    {{- if .Values.VOLUME_DRIVER_OPT}}
    driver_opts:
      {{.Values.VOLUME_DRIVER_OPT}}
    {{- end}}
