name: "Logcentral"
description: "EEA Centralized logging based on Docker and Graylog2"
version: "18-1"
category: "Logging"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.logcentral/
labels:
  io.rancher.certified: EEA
