name: "EEA - PostgreSQL (Cluster)"
description: "PostgreSQL master/replica cluster"
version: "9.4-rancher1"
category: "Storage"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
