version: '2'
services:

  memcached:
    image: memcached:1.6.20-alpine
    mem_limit: 1g
    mem_reservation: 1g
    command:
    - "-m"
    - "1024"
    - "-I"
    - "50m"
    environment:
      TZ: ${TZ}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:host_label_ne: ${HOST_LABELS}
      eu.europa.saas.memcached3: 'true'

  zeo:
    #image: eeacms/clms-backend:4.2
    image: plone/plone-zeo:5.3
    ports:
    - "8100:8100"
    mem_reservation: ${ZEO_MEM_LIMIT}
    mem_limit: ${ZEO_MEM_LIMIT}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.zeo3: 'true'
    volumes:
    - ${DATA_VOLUME_NAME}:/data
    environment:
#      ZOPE_MODE: "zeo"
      TZ: ${TZ}
      CRON_JOBS: "${ZEO_CRON_JOBS}"
#    command:
#    - zeo

  plone:
    image: eeacms/clms-backend:6.0.15-120
    ports:
    - "8080"
    mem_reservation: ${MEM_LIMIT}
    mem_limit: ${MEM_LIMIT}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.plone3: 'true'
      {{- if eq .Values.TRAEFIK_ENABLE "true" }}
      traefik.enable: true
      {{- if eq .Values.TRAEFIK_ENABLE_POST_RL "true" }}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth: '2'
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.average: {{.Values.TRAEFIK_RATE_LIMIT_AVG}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.period: {{.Values.TRAEFIK_RATE_LIMIT_PERIOD}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.burst: {{.Values.TRAEFIK_RATE_LIMIT_BURST}}
      traefik.http.services.{{.Values.TRAEFIK_SERVICE}}-post.loadbalancer.server.port: {{.Values.TRAEFIK_LOADBALANCER_PORT}}
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.middlewares: {{.Values.TRAEFIK_SERVICE}}-post-ratelimit
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.rule: Host(`{{.Values.TRAEFIK_URL}}`) && PathPrefix(`/VirtualHostBase/https/`) && Method(`POST`)
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.service: {{.Values.TRAEFIK_SERVICE}}-post@rancher
      {{- end }}
      {{- if eq .Values.TRAEFIK_ENABLE_DWLD_RL "true" }}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth: '2'
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.average: {{.Values.TRAEFIK_DWN_RATE_LIMIT_AVG}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.period: {{.Values.TRAEFIK_DWN_RATE_LIMIT_PERIOD}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.burst: {{.Values.TRAEFIK_DWN_RATE_LIMIT_BURST}}
      traefik.http.services.{{.Values.TRAEFIK_SERVICE}}-dwn.loadbalancer.server.port: {{.Values.TRAEFIK_LOADBALANCER_PORT}}
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.middlewares: {{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.rule: Host(`{{.Values.TRAEFIK_URL}}`) && PathPrefix(`/VirtualHostBase/https/{{.Values.TRAEFIK_URL}}:443/Plone/VirtualHostRoot/_vh_api/@datarequest_post`) && Method(`POST`)
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.service: {{.Values.TRAEFIK_SERVICE}}-dwn@rancher
      {{- end }}
      {{- end }}
    links:
    - postfix
    - memcached
    - zeo
    - postgres
    depends_on:
    - postfix
    - memcached
    - zeo
    - postgres
    environment:
      ZEO_ADDRESS: zeo:8100
      ZOPE_MODE: "zeo_client"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "${SENTRY_ENVIRONMENT}"
      SENTRY_RELEASE: '6.0.15-120'
      BACKEND_VERSION: '6.0.15-120'
      TZ: ${TZ}
      CRON_JOBS: "${ZOPE_CRON_JOBS}"
      DEFAULT_PUBLISHER: "${DEFAULT_PUBLISHER}"
      DEFAULT_ORGANISATIONS: "${DEFAULT_ORGANISATIONS}"
      STATIC_BANNER_ENABLED: "${STATIC_BANNER_ENABLED}"
      DYNAMIC_BANNER_ENABLED: "${DYNAMIC_BANNER_ENABLED}"
      GRAYLOG: "logcentral.eea.europa.eu:12201"
      GRAYLOG_FACILITY: "${SERVER_NAME}"
      CDSE_MONITOR_URL: "${CDSE_MONITOR_URL}"
      CDSE_MONITOR_VIEW_TOKEN: "${CDSE_MONITOR_VIEW_TOKEN}"
      CDSE_USAGE_URL: "${CDSE_USAGE_URL}"
      CDSE_USAGE_VIEW_TOKEN: "${CDSE_USAGE_VIEW_TOKEN}"
      CDSE_USAGE_LIMITS_EMAIL_TO: "${CDSE_USAGE_LIMITS_EMAIL_TO}"
      PLONE_AUTH_TOKEN: "${PLONE_AUTH_TOKEN}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOWNLOADTOOL_DB_DSN: "dbname=${POSTGRES_DBNAME} user=${POSTGRES_DBUSER} password=${POSTGRES_DBPASS} host=postgres"

  plone-cdse-monitor:
    image: eeacms/clms-backend:6.0.15-120
    ports:
    - "8080"
    mem_reservation: ${MEM_LIMIT}
    mem_limit: ${MEM_LIMIT}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.plone3: 'true'
      {{- if eq .Values.TRAEFIK_ENABLE "true" }}
      traefik.enable: true
      {{- if eq .Values.TRAEFIK_ENABLE_POST_RL "true" }}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth: '2'
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.average: {{.Values.TRAEFIK_RATE_LIMIT_AVG}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.period: {{.Values.TRAEFIK_RATE_LIMIT_PERIOD}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-post-ratelimit.ratelimit.burst: {{.Values.TRAEFIK_RATE_LIMIT_BURST}}
      traefik.http.services.{{.Values.TRAEFIK_SERVICE}}-post.loadbalancer.server.port: {{.Values.TRAEFIK_LOADBALANCER_PORT}}
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.middlewares: {{.Values.TRAEFIK_SERVICE}}-post-ratelimit
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.rule: Host(`{{.Values.TRAEFIK_URL}}`) && PathPrefix(`/VirtualHostBase/https/`) && Method(`POST`)
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-post.service: {{.Values.TRAEFIK_SERVICE}}-post@rancher
      {{- end }}
      {{- if eq .Values.TRAEFIK_ENABLE_DWLD_RL "true" }}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth: '2'
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.average: {{.Values.TRAEFIK_DWN_RATE_LIMIT_AVG}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.period: {{.Values.TRAEFIK_DWN_RATE_LIMIT_PERIOD}}
      traefik.http.middlewares.{{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit.ratelimit.burst: {{.Values.TRAEFIK_DWN_RATE_LIMIT_BURST}}
      traefik.http.services.{{.Values.TRAEFIK_SERVICE}}-dwn.loadbalancer.server.port: {{.Values.TRAEFIK_LOADBALANCER_PORT}}
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.middlewares: {{.Values.TRAEFIK_SERVICE}}-dwn-ratelimit
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.rule: Host(`{{.Values.TRAEFIK_URL}}`) && PathPrefix(`/VirtualHostBase/https/{{.Values.TRAEFIK_URL}}:443/Plone/VirtualHostRoot/_vh_api/@datarequest_post`) && Method(`POST`)
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-dwn.service: {{.Values.TRAEFIK_SERVICE}}-dwn@rancher
      {{- end }}
      {{- end }}
    links:
    - postfix
    - memcached
    - zeo
    - postgres
    depends_on:
    - postfix
    - memcached
    - zeo
    - postgres
    environment:
      ZEO_ADDRESS: zeo:8100
      ZOPE_MODE: "zeo_client"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "${SENTRY_ENVIRONMENT}"
      SENTRY_RELEASE: '6.0.15-120'
      BACKEND_VERSION: '6.0.15-120'
      TZ: ${TZ}
      CRON_JOBS: "${ZOPE_CRON_JOBS}"
      DEFAULT_PUBLISHER: "${DEFAULT_PUBLISHER}"
      DEFAULT_ORGANISATIONS: "${DEFAULT_ORGANISATIONS}"
      STATIC_BANNER_ENABLED: "${STATIC_BANNER_ENABLED}"
      DYNAMIC_BANNER_ENABLED: "${DYNAMIC_BANNER_ENABLED}"
      GRAYLOG: "logcentral.eea.europa.eu:12201"
      GRAYLOG_FACILITY: "${SERVER_NAME}"
      CDSE_MONITOR_URL: "${CDSE_MONITOR_URL}"
      CDSE_MONITOR_VIEW_TOKEN: "${CDSE_MONITOR_VIEW_TOKEN}"
      PLONE_AUTH_TOKEN: "${PLONE_AUTH_TOKEN}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOWNLOADTOOL_DB_DSN: "dbname=${POSTGRES_DBNAME} user=${POSTGRES_DBUSER} password=${POSTGRES_DBPASS} host=postgres"

  redis:
    image: redis:7.4.7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    privileged: true
    mem_limit: 256m
    mem_reservation: 128m
    ports:
      - "6379"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: ${TZ}

  postgres:
    image: eeacms/postgres:16s
    mem_limit: 1g
    mem_reservation: 512m
    volumes:
    - ${POSTGRES_VOLUME_NAME}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_DBUSER: ${POSTGRES_DBUSER}
      POSTGRES_DBPASS: ${POSTGRES_DBPASS}
      TZ: ${TZ}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  asyncjobs:
    image: eeacms/clms-async-jobs:1.0.1
    depends_on:
      - redis
      - plone
    environment:
      PLONE_URL: "http://plone:8080/Plone"
      PLONE_AUTH_TOKEN: "${PLONE_AUTH_TOKEN}"

      # Redis connection
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

      # Bull board
      PORT: 3100

      TZ: ${TZ}
    ports:
      - "3100:3100"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  varnish:
    image: eeacms/plone-varnish:7.7-1.1
    mem_reservation: 1g
    mem_limit: 1g
    ports:
    - "8080"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.varnish3: 'true'
      {{- if eq .Values.TRAEFIK_ENABLE "true" }}
      traefik.enable: true
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-default.rule: Host(`{{.Values.TRAEFIK_URL}}`) && PathPrefix(`/VirtualHostBase/https/`)
      traefik.http.services.{{.Values.TRAEFIK_SERVICE}}-default.loadbalancer.server.port: {{.Values.TRAEFIK_LOADBALANCER_PORT}}
      traefik.http.routers.{{.Values.TRAEFIK_SERVICE}}-default.service: {{.Values.TRAEFIK_SERVICE}}-default@rancher
      {{- end }}
    links:
    - haproxy
    depends_on:
    - haproxy
    environment:
      TZ: "${TZ}"
      VARNISH_BACKEND: "${VARNISH_BACKEND}"
      VARNISH_BACKEND_PORT: '8080'
      VARNISH_HTTP_PORT: '8080'
      VARNISH_SIZE: "${CACHE_SIZE}"
      VARNISH_DNS_TTL: 20s
      VARNISH_BERESP_TTL: "${VARNISH_BERESP_TTL}"
      VARNISH_BERESP_GRACE: "${VARNISH_BERESP_GRACE}"
      VARNISH_BERESP_KEEP: "${VARNISH_BERESP_KEEP}"
      VARNISH_GZIP_ENABLED: "${VARNISH_GZIP_ENABLED}"
      VARNISH_GZIP_JSON_ENABLED: "${VARNISH_GZIP_JSON_ENABLED}"
      VARNISH_CLEAR_OTHER_COOKIES: ${VARNISH_CLEAR_OTHER_COOKIES}

  haproxy:
    image: eeacms/haproxy:1.8-1.7
    mem_limit: 128m
    mem_reservation: 128m
    ports:
    - "8080"
    - "1936"
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.haproxy3: 'true'
    links:
    - plone
    depends_on:
    - plone
    environment:
      STATS_AUTH: "${HAPROXY_AUTH}"
      FRONTEND_PORT: "8080"
      BACKENDS_PORT: "8080"
      BACKENDS: "plone"
      DNS_ENABLED: "true"
      INTER: "20s"
      DOWN_INTER: "5s"
      FAST_INTER: "15s"
      TIMEOUT_SERVER: "120s"
      TIMEOUT_CLIENT: "120s"
      TZ: "${TZ}"
      HTTPCHK: "HEAD /haproxycheck"

  postfix:
    image: eeacms/postfix:3.5-1.2
    environment:
      MTP_HOST: ${POSTFIX_SERVER_NAME}
      MTP_RELAY: ${POSTFIX_RELAY}
      MTP_PORT: ${POSTFIX_PORT}
      MTP_PASS: ${POSTFIX_PASS}
      MTP_USER: ${POSTFIX_USER}
      TZ: ${TZ}
    mem_limit: 256m
    mem_reservation: 128m
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: ${HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.postfix3: 'true'

  cdsemonitor:
    image: curlimages/curl:8.8.0
    entrypoint:
    - /bin/sh
    - -c
    - curl -v "${CDSE_MONITOR_URL}?token=${CDSE_MONITOR_VIEW_TOKEN}"
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      cron.schedule: '0 0 * * * *'

  cdseusage:
    image: curlimages/curl:8.8.0
    entrypoint:
    - /bin/sh
    - -c
    - curl -v "${CDSE_USAGE_URL}?token=${CDSE_USAGE_VIEW_TOKEN}"
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      cron.schedule: '0 30 8 * * *'

  zeopack:
    image: eeacms/clms-backend:6.0.15-120
    ports:
    - "8080"
    mem_reservation: ${MEM_LIMIT}
    mem_limit: ${MEM_LIMIT}
    labels:
      io.rancher.container.start_once: 'true'
      cron.schedule: 00 01 * * Sun
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      eu.europa.saas.plone3: 'true'
    links:
    - postfix
    - memcached
    - zeo
    - postgres
    depends_on:
    - postfix
    - memcached
    - zeo
    - postgres
    environment:
      ZEO_ADDRESS: zeo:8100
      ZOPE_MODE: "zeo_client"
      SENTRY_DSN: "${SENTRY_DSN}"
      SENTRY_SITE: "${SENTRY_SITE}"
      SENTRY_ENVIRONMENT: "${SENTRY_ENVIRONMENT}"
      SENTRY_RELEASE: '6.0.15-120'
      BACKEND_VERSION: '6.0.15-120'
      TZ: ${TZ}
      DEFAULT_PUBLISHER: "${DEFAULT_PUBLISHER}"
      DEFAULT_ORGANISATIONS: "${DEFAULT_ORGANISATIONS}"
      STATIC_BANNER_ENABLED: "${STATIC_BANNER_ENABLED}"
      DYNAMIC_BANNER_ENABLED: "${DYNAMIC_BANNER_ENABLED}"
      DOWNLOADTOOL_DB_DSN: "dbname=${POSTGRES_DBNAME} user=${POSTGRES_DBUSER} password=${POSTGRES_DBPASS} host=postgres"
    stdin_open: true
    tty: true
    command:
    - /app/bin/zeopack
    - zeo:8100

volumes:
  {{ .Values.DATA_VOLUME_NAME }}:
    driver: ${DATA_VOLUME_DRIVER}
    {{- if eq .Values.VOLUME_EXTERNAL "yes"}}
    external: true
    {{- end}}
    driver_opts:
      {{.Values.DATA_VOLUME_DRIVER_OPTS}}
  {{ .Values.POSTGRES_VOLUME_NAME }}:
    driver: ${POSTGRES_VOLUME_DRIVER}
    {{- if eq .Values.POSTGRES_VOLUME_EXTERNAL "yes"}}
    external: true
    {{- end}}
    driver_opts:
      {{.Values.POSTGRES_VOLUME_DRIVER_OPTS}}
