name: "EEA WWW - Sync"
description: "Sync EEA WWW blobs and static resources across Rancher Environments"
version: "1.1-rancher1"
category: "Backup"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
