name: "Taskman"
description: "taskman.eionet.europa.eu - Redmine based Agile project management tool"
version: "4.2-1.9"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.docker.redmine
labels:
  io.rancher.certified: EEA

