version: '2'
services:
  master:
    image: rancher/external-service
  admin:
    image: eeacms/postgres:9.6-3.5
    mem_limit: 16g
    mem_reservation: 1g
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${SERVICE_HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      POSTGRES_HOST: "master"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGHOST: "master"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_CRONS: "${POSTGRES_CRONS}"
      TZ: "${TZ}"
    volumes:
    - www-postgres-dump:/postgresql.backup
    stdin_open: true
    tty: true
    command:
    - cat

  memcached:
    image: memcached:1.5.20
    mem_limit: 8g
    mem_reservation: 1g
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: ${CACHE_HOST_LABELS}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    environment:
      TZ: "${TZ}"
    command:
    - "-m"
    - "${CACHE_SIZE}"

  {{- if .Values.FLUSH_MEMCACHED_CRON}}
  flush_memcached:
    image: alpine:3.11
    entrypoint:
     - sh
     - -c
     - echo 'flush_all' | nc memcached 11211
     labels:
       io.rancher.container.pull_image: always
       io.rancher.container.start_once: 'true'
       io.rancher.scheduler.affinity:host_label: ${CACHE_HOST_LABELS}
       io.rancher.container.hostname_override: container_name
       cron.schedule: "${FLUSH_MEMCACHED_CRON}"
   {{- end}}

      

volumes:
  www-postgres-dump:
    external: true
