name: "PAM â€” Elastic app"
description: "Elasticsearch app for climate change mitigation policies and measures in Europe."
version: "5.0.4"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
