name: "Community"
description: "EEA Forum"
version: "1.0"
category: "Chat"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.community/
labels:
  io.rancher.certified: EEA
