name: "Matomo"
description: "Matomo (formerly piwik) is a web analytics platform."
version: "5.3.2-1"
category: "Web Analytics"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://matomo.org/
labels:
  io.rancher.certified: EEA
