version: '2'
services:
  frontend:
    image: eeacms/clms-frontend:1.0.17
    ports:
    - "3000"
    mem_limit: 1g
    mem_reservation: 1g
    depends_on:
    - backend
    links:
    - backend
    environment:
      API_PATH: ${API_PATH}
      {{- if eq .Values.DEBUG "Yes" }}
      DEBUG: '*'
      {{- end}}
      INTERNAL_API_PATH: ${INTERNAL_API_PATH}
      PORT: '3000'
      TZ: "${TZ}"

  backend:
    image: rancher/dns-service
    external_links:
    - ${BACKEND}:backend

