name: "Volto - Marine"
description: "Volto - Marine: React-based frontend"
version: "3.11.0.demo.02"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/marine-frontend
labels:
  io.rancher.certified: EEA
