name: "Copernicus Insitu Frontend - Plone 6"
description: "Plone 6 Volto Frontend for Copernicus In-situ"
version: "2.30.0-1"
category: "CMS"
maintainer: "EEA: IDM2 N-Team"
license: "GPLv3"
projectURL: https://github.com/eea/insitu-frontend
labels:
  io.rancher.certified: EEA
