name: "Volto - Energy Union"
description: "Volto - Energy Union: React-based frontend"
version: "v1.3"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
