name: "CLMS Backend - Plone"
description: "CLMS backend plone site"
version: "6.0.15-25"
category: "Applications"
maintainer: "EEA"
license: "GPLv3"
projectURL: https://github.com/eea/eea.docker.plone.clms/tree/master
labels:
  io.rancher.certified: Eionet
