name: "Volto - Sustainability"
description: "Volto - Sustainability: React-based frontend"
version: "0"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
