name: "Volto - Industry"
description: "Volto - Industry: React-based frontend"
version: "3.28.0"
category: "CMS"
maintainer: "EEA: IDM2 N-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems
labels:
  io.rancher.certified: EEA
