logspout:
  restart: always
  environment:
    LOGSPOUT: 'ignore'
    ROUTE_URIS: "${route_uri}"
  log_driver: ''
  labels:
    io.rancher.scheduler.global:'true'
    io.rancher.container.hostname_override:container_name
    io.rancher.scheduler.affinity:host_label_ne:service=fileserver,graylogpool=yes
  tty: true
  log_opt: {}
  image: rancher/logspoutÂ­logstash:v0.2.0
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
  
