name: "UNS"
description: "Unified Notification System"
version: "2022-04-11T1042-1"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.rancher.catalog/blob/master/templates/uns/README.md
labels:
  io.rancher.certified: EEA
