version: '2'
services:
  frontend:
    image: eeacms/marine-frontend:1.11.0.rc-eea-design.87
    ports:
    #- "3000"
    - 52372:3000/tcp
    mem_limit: 1g
    mem_reservation: 1g
    depends_on:
    - backend
    links:
    - backend
    environment:
      PORT: '3000'
      {{- if eq .Values.DEBUG "Yes" }}
      DEBUG: '*'
      {{- end}}
      RAZZLE_ALLOWED_CORS_DESTINATIONS: ${RAZZLE_ALLOWED_CORS_DESTINATIONS}
      RAZZLE_DEMO_SITE: ${RAZZLE_DEMO_SITE}
      RAZZLE_BANNER_HEADER: ${RAZZLE_BANNER_HEADER}
      RAZZLE_BANNER_MESSAGE: ${RAZZLE_BANNER_MESSAGE}
      RAZZLE_FRONTEND_VERSION: '1.11.0.rc-eea-design.87'
      RAZZLE_MATOMO_SITE_ID: ${RAZZLE_MATOMO_SITE_ID}
      RAZZLE_MATOMO_URL: ${RAZZLE_MATOMO_URL}
      RAZZLE_PROXY_ES_DSN_globalsearch: ${RAZZLE_PROXY_ES_DSN_globalsearch}
      RAZZLE_PROXY_QA_DSN_globalsearch: ${RAZZLE_PROXY_QA_DSN_globalsearch}
      RAZZLE_PROXY_ES_DSN_marinemeasure: ${RAZZLE_PROXY_ES_DSN_marinemeasure}
      RAZZLE_PROXY_QA_DSN_marinemeasure: ${RAZZLE_PROXY_QA_DSN_marinemeasure}
      RAZZLE_SENTRY_DSN: ${RAZZLE_SENTRY_DSN}
      RAZZLE_SENTRY_RELEASE: '1.11.0.rc-eea-design.87'
      SENTRY_RELEASE: '1.11.0.rc-eea-design.87'
      SENTRY_URL: ${SENTRY_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SENTRY_ORG: ${SENTRY_ORG}
      SENTRY_PROJECT: ${SENTRY_PROJECT}
      RAZZLE_PROXY_ES_DSN: ''
      RAZZLE_BACKEND_NAME: "marine-backend"
      RAZZLE_INTERNAL_API_PATH: ${RAZZLE_INTERNAL_API_PATH}
      RAZZLE_API_PATH: ${RAZZLE_API_PATH}
      RAZZLE_PREFIX_PATH: ${RAZZLE_PREFIX_PATH}
      TZ: ${TZ}
      VOLTO_ROBOTSTXT: ${VOLTO_ROBOTSTXT}
    labels:
      {{- if .Values.HOST_LABELS}}
      io.rancher.scheduler.affinity:host_label: ${HOST_LABELS}
      {{- else}}
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      {{- end}}
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  backend:
    image: rancher/dns-service
    external_links:
    - ${BACKEND}:backend
