name: "Elasticsearch 6.0 engine"
description: "EEA Elasticsearch 6.0 cluster to be used by elastic apps"
version: "6.1.1"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
