name: "Elasticsearch 6 engine"
description: "EEA Elasticsearch 6 cluster to be used by elastic apps"
version: "6.2.3"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
