name: "EEA - PostgreSQL (External)"
description: "PostgreSQL external service with backup support (Amazon Aurora)"
version: "9.6-rancher2"
category: "Storage"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.www
labels:
  io.rancher.certified: EEA
