version: "2"
services:
  apache:
    image: eeacms/apache:2.4-2.1-alpine
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - varnish
    environment:
      APACHE_MODULES: "${APACHE_MODULES}"
      APACHE_CONFIG: "${APACHE_CONFIG}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads

  varnish:
    image: eeacms/varnish-copernicus-land:1.0
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      VARNISH_BACKEND_HOST: haproxy
      VARNISH_BACKEND_PORT: '5000'
      VARNISH_MEMORY: 2G
      LOGSPOUT: "ignore"
    links:
    - haproxy

  haproxy:
    image: eeacms/haproxy:1.7-4.1
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    ports:
    - "1936:1936"
    links:
    - plone
    environment:
      TZ: "${TZ}"
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      TIMEOUT_SERVER: "180000"
      TIMEOUT_CLIENT: "180000"
      STATS_AUTH: "${HAPROXY_STATS_AUTH}"

  memcached:
    image: memcached:1
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "${TZ}"
    command:
    - -m
    - "2048"

  postfix:
    image: eeacms/postfix:eionet
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "${TZ}"
      MTP_HOST: "eea.europa.eu"

  plone:
    image: eeacms/plone-copernicus-land:18.2.15-2.15
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_client"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads

  async:
    image: eeacms/plone-copernicus-land:18.2.15-2.15
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    links:
    - zeoserver
    - memcached
    - postfix
    environment:
      TZ: "${TZ}"
      ZOPE_MODE: "zeo_async"
      LAND_DOWNLOADS_SRC_PATH: /data/downloads/landfiles/src/
      LAND_DOWNLOADS_DST_PATH: /data/downloads/landfiles/dst/
      LAND_DOWNLOADS_STATIC_PATH: "${LAND_DOWNLOADS_STATIC_PATH}"
      SENTRY_DSN: "${SENTRY_DSN}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/data/downloads

  zeoserver:
    image: plone/zeoserver:2.13.23-alpine
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_data:/data
    environment:
      TZ: "${TZ}"

  container-crontab:
    image: rancher/container-crontab:v0.3.0
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/rancher:/var/lib/rancher
    environment:
      DOCKER_API_VERSION: "${DOCKER_API_VERSION}"

  sync-proxy:
    image: nginx:1.13-alpine
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      NGINX_CONF: "${SYNC_PROXY_CONFIG}"
    command:
      - /bin/sh
      - -c
      - 'echo $$NGINX_CONF > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    restart: "always"


  landfiles-sync:
    image: eeacms/copernicus-land-scripts:sync-1.1
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      SOURCE_DIRECTORY: "${SYNC_REMOTE_PATH}"
      TARGET_DIRECTORY: "${SYNC_TARGET_PATH}"
      RCLONE_CONFIG_REMOTE_URL: "${SYNC_REMOTE_URL}"
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads

  landfiles-cleanup:
    image: eeacms/copernicus-land-scripts:cleanup-1.0
    labels:
      io.rancher.scheduler.affinity:host_label: "${HOST_LABELS}"
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
      io.rancher.container.start_once: "true"
      cron.schedule: "0 0 0 * * ?"
    environment:
      TZ: "${TZ}"
      TARGET_DIRECTORY: /downloads/landfiles/dst/
    volumes:
    - {{ .Values.VOLUME_PREFIX }}land_downloads:/downloads

volumes:
  {{ .Values.VOLUME_PREFIX }}land_data:
    driver: rancher-nfs
    external: true
  {{ .Values.VOLUME_PREFIX }}land_downloads:
    driver: rancher-nfs
    external: true
