version: "3"

services:
  frontend:
    image: eeacms/clms-frontend:1.0.2
    ports:
      - "${FRONTEND:-8000}:3000"
    depends_on:
      - ploneapi
    environment:
      API_PATH: "http://localhost:${BACKEND:-8080}/Plone"
      INTERNAL_API_PATH: "http://ploneapi:${BACKEND:-8080}/Plone"

  ploneapi:
    image: eeacms/clms-backend:latest
    ports:
      - "${BACKEND:-8080}:8080"
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:${FRONTEND:-8000},http://127.0.0.1:${FRONTEND:-8000}"
    depends_on:
      - memcached
    volumes:
      - data:/data

  memcached:
    image: memcached
    command:
      - "-m"
      - "512"
