name: "Climate Board Advisory Frontend - Plone 6"
description: "Plone 6 Volto Frontend for Climate Board Advisory"
version: "1.9.0"
category: "CMS"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: https://github.com/eea/advisory-board-frontend
labels:
  io.rancher.certified: EEA
