name: "Copernicus - Insitu Deployment"
description: "Copernicus Insitu website."
version: "1.3"
category: "Repository"
maintainer: "EEA: IDM2"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.copernicus/
