name: "EEA - ODP CKAN"
description: "EU Open Data Portal CKAN client"
version: "2.0"
category: "Applications"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs//IT-systems/eea.odpckan/
labels:
  io.rancher.certified: EEA
