name: "FISE â€” Elastic app"
description: "Elasticsearch app for FISE."
version: "3.0.25"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
