name: "CO2 vans â€” Elastic app"
description: "Elasticsearch app for CO2 emmisions from vans."
version: "1.0.0"
category: "Search services"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.esbootstrap/
labels:
  io.rancher.certified: EEA
