name: "BDR test"
description: "BDR Eionet"
version: "5.9.4-229"
category: "Backend"
maintainer: "EEA: P-Team"
license: "GPLv3"
projectURL: https://github.com/eea/eea.rancher.catalog/blob/master/templates/bdr/README.md
labels:
  io.rancher.certified: EEA
