name: "SonarQube"
description: "[DEPRECATED / MIGRATED TO RANCHER2] SonarQube - an open source quality management platform"
version: "25.4.0.105899"
category: "Monitoring"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
labels:
  io.rancher.certified: EEA
