name: "Copernicus - Land Deployment"
description: "Copernicus Land website."
version: "1.4"
category: "Repository"
maintainer: "EEA: IDM2 A-Team"
license: "GPLv3"
projectURL: http://eea.github.io/docs/IT-systems/eea.docker.copernicus//
